name: Build and deploy Node.js app to Azure Web App - kalpana2024

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install, build, and test client
        run: |
          cd client
          npm install
          npm run build --if-present
          npm run test --if-present
        shell: bash

      - name: Install, build, and test backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present
        shell: bash

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8772601BB1FD45408683FE2976DD754A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD3107E95DBB4747ADCBA3418B427B2D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCF761F9684542D296E960DBA974F863 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'kalpana2024'
          slot-name: 'Production'
          package: .
